export const wordCloudSkillsGrid = [
  [
    { name: "System Architecture", radius: 10 },
    { name: "LangChain", radius: 12 },
    { name: "Tailwind CSS", radius: 7 },
    { name: "Zustand", radius: 7 },
    { name: "MongoDB", radius: 13 },
    { name: "RAG", radius: 6 },
    { name: "CosmosDB", radius: 8 },
    { name: "Okta", radius: 9 },
  ],
  [
    { name: "Full Stack", radius: 15 },
    { name: "Authentication", radius: 10 },
    { name: "React", radius: 20 },
    { name: "SSO", radius: 9 },
    { name: "Agile", radius: 13 },
    { name: "Storybook", radius: 7 },
    { name: "Azure AI Search", radius: 8 },
    { name: "DevOps", radius: 10 },
  ],
  [
    { name: "Microservices", radius: 7 },
    { name: "OpenStreetMap", radius: 10 },
    { name: "Java", radius: 11 },
    { name: "MUI", radius: 14 },
    { name: "Stripe", radius: 9 },
    { name: "Next.js", radius: 13 },
    { name: "OpenAI", radius: 16 },
    { name: "Product-driven development", radius: 7 },
  ],
  [
    { name: "Docker", radius: 7 },
    { name: "Node.js", radius: 18 },
    { name: "Data Visualization", radius: 7 },
    { name: "Ionic", radius: 11 },
    { name: "Mapbox GL JS", radius: 12 },
    { name: "Apollo", radius: 7 },
    { name: "Azure App Services", radius: 8 },
    { name: "Product Management", radius: 7 },
  ],
  [
    { name: "Backend", radius: 13 },
    { name: "CI/CD", radius: 8 },
    { name: "NestJS", radius: 17 },
    { name: "GeoJSON", radius: 10 },
    { name: "Redux", radius: 7 },
    { name: "Kotlin", radius: 12 },
    { name: "LLMs", radius: 9 },
    { name: "FastAPI", radius: 11 },
  ],
  [
    { name: "React Native", radius: 14 },
    { name: "TypeScript", radius: 20 },
    { name: "Team Collaboration", radius: 8 },
    { name: "Agile", radius: 7 },
    { name: "Prompt Engineering", radius: 12 },
    { name: "Travel & Transportation", radius: 9 },
    { name: "Jest", radius: 8 },
    { name: "Figma", radius: 7 },
  ],
  [
    { name: "GraphQL", radius: 17 },
    { name: "Shopify", radius: 10 },
    { name: "Android", radius: 13 },
    { name: "LlamaIndex", radius: 14 },
    { name: "Gen AI", radius: 15 },
    { name: "Azure OpenAI", radius: 14 },
    { name: "UI/UX", radius: 11 },
    { name: "Gitlab", radius: 10 },
  ],
  [
    { name: "Kotlin", radius: 8 },
    { name: "Agentic Gen AI", radius: 8 },
    { name: "Python", radius: 9 },
    { name: "Frontend", radius: 13 },
    { name: "AWS", radius: 9 },
    { name: "Data Governance", radius: 8 },
    { name: "Nx", radius: 11 },
    { name: "Firebase", radius: 7 },
  ],
];
